env:
  browser: true
  es6: true
  node: true

parserOptions:
  ecmaVersion: 2017
  sourceType: module

overrides:
  - files: "**/*.js"
    extends:
      - eslint:recommended

  - files: "**/*.ts"
    extends:
      - airbnb-typescript/base
    parserOptions:
      project: ./tsconfig.json
    rules:
      no-proto: off
      no-underscore-dangle: [error, {allowAfterThis: true}]
      import/no-cycle: off
