extends:
  - eslint:recommended

env:
  browser: true
  es6: true
  node: true

parserOptions:
  ecmaVersion: 2017
  sourceType: module

rules:
  indent: [error, 4]

overrides:
  - files: "**/*.ts"
    extends:
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
