language: node_js

node_js:
  - "8"
  - "9"

after_success:
  - npm install codeclimate-test-reporter
  - CODECLIMATE_REPO_TOKEN=f0abd0bd51bae2cc59f3acbfb80978067b6b15309cc5e6e7f1269e6afaf21e3e ./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info
