name: security

on:
  push:
    branches: [stable, dev]
  pull_request:
    branches: [dev]
  schedule:
    - cron: '0 0 * * 5'

jobs:
  security:
    name: security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      # If this run was triggered by a pull request event, then checkout
      # the head of the pull request instead of the merge commit.
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
      - uses: github/codeql-action/init@v1
        with:
          languages: javascript
      - uses: github/codeql-action/analyze@v1
